Dz6 add avatar component
js-tasks-ru/htmlcss-20220210_ivan87 pull request #12
Opened 2022-03-07 22:00 UTC by Xatabch

2022-03-07 22:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-10 20:56 UTC, GSemikozov requested changes

2022-03-10 20:56 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
лучше сделать как на занятии (с дополнительным враппером), поскольку часто помимо самой картинки аватара добавляют еще например элемент индикатора/статуса (онлайн/оффлайн)

2022-03-11 16:36 UTC, GSemikozov approved these changes

2022-03-11 16:36 UTC, merged