Dz6 responsive pages
js-tasks-ru/htmlcss-20220210_ivan87 pull request #16
Opened 2022-03-13 09:03 UTC by Xatabch

2022-03-13 09:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-13 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-13 20:31 UTC, GSemikozov requested changes

2022-03-13 20:31 UTC, GSemikozov commented on components/calendar/index.css
> +    .calendar_preview .calendar__title {
здесь и ниже совсем не обязательно использовать вложенные селекторы (указывать в начале .calendar_preview) и сложные селеккторы по типу .calendar__item.calendar__item_day

2022-03-13 20:31 UTC, GSemikozov commented on components/histogram/index.css
> +    .histogram_preview .histogram__title {
та же история что и выше

2022-03-14 21:08 UTC, Xatabch commented on components/calendar/index.css
> +    .calendar_preview .calendar__title {
но если мне необходимо чтобы данные стили применялись именно для превью, что делать тогда?

2022-03-15 21:13 UTC, GSemikozov commented on components/calendar/index.css
> +    .calendar_preview .calendar__title {
да, мой косяк, все верно

2022-03-15 21:13 UTC, GSemikozov approved these changes

2022-03-15 21:13 UTC, merged