Dz7 add input
js-tasks-ru/htmlcss-20220210_ivan87 pull request #18
Opened 2022-03-14 21:02 UTC by Xatabch

2022-03-14 21:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-14 21:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-16 19:07 UTC, GSemikozov requested changes

2022-03-16 19:07 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form {
это все-таки не форма, а составляющая формы, то есть например .form-group)

2022-03-16 19:07 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    max-height: 56px;
просто height

2022-03-17 22:24 UTC, Xatabch commented on 07-lection5/04-input/input.css
> +.form {
поправил

2022-03-17 22:24 UTC, Xatabch commented on 07-lection5/04-input/input.css
> +    max-height: 56px;
поправил

2022-03-20 14:42 UTC, GSemikozov submitted a review, later dismissed

2022-03-20 14:42 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-03-25 19:14 UTC, GSemikozov approved these changes

2022-03-25 19:15 UTC, merged